name = "TrajectoryBundles"
uuid = "6356fb03-8c35-4dfb-8dca-145006c345e7"
authors = ["Aaron Trowbridge"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
